parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
env:
  node: true

plugins:
  - "@typescript-eslint"
  - react
  - import

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended

settings:
  import/resolver:
    typescript: true
    node: true

rules:
  import/order: [1, { newlines-between: always }]
