on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: daeuniverse/dae-wing
          path: dae-wing

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: latest

      - name: build daed
        run: |
          pnpm install
          pnpm build

      - name: build dae-wing
        run: |
          cd dae-wing
          make deps
          go build .

      - name: bundle
        run: |
          cd dae-wing
          make WEB_DIST=../dist/ bundle

      - name: upload web
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: dist

      - name: upload bundled
        uses: actions/upload-artifact@v3
        with:
          name: bundled
          path: dae-wing/dae-wing

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: download web
        uses: actions/download-artifact@v3
        with:
          name: web
          path: dist/

      - name: download bundled
        uses: actions/download-artifact@v3
        with:
          name: bundled
          path: dae-wing/

      - name: pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
