name: build & release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: daeuniverse/dae-wing
          path: dae-wing

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: latest

      - name: build daed
        run: |
          pnpm install
          pnpm build

      - name: build dae-wing
        run: |
          cd dae-wing
          make deps
          go build .

      - name: bundle
        run: |
          cd dae-wing
          make WEB_DIST=../dist/ bundle

      - name: upload artifact - web
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: dist

      - name: upload artifact - bundled
        uses: actions/upload-artifact@v3
        with:
          name: bundled
          path: dae-wing/dae-wing

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: download artifact - web
        uses: actions/download-artifact@v3
        with:
          name: web
          path: dist/

      - name: download artifact - bundled
        uses: actions/download-artifact@v3
        with:
          name: bundled
          path: dae-wing/

      - name: publish github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: docker - login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker - publish image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: daeuniverse/daed:latest
