on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: latest

      - name: build
        run: |
          pnpm install
          pnpm build

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dashboard/dist

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist/
