name: Synchronize Upstream

on:
  workflow_dispatch:
    inputs:
      wing-head:
        type: string
        required: true
        default: main
      wing-sync-message:
        type: string
        required: true
        default: 'chore(sync): upgrade dae-wing'
      pr-branch:
        type: string
        required: true
        default: sync-upstream

jobs:
  sync-wing:
    runs-on: ubuntu-latest
    if: ${{ inputs.wing-head }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: main

      - name: Sync dae-wing upstream
        run: |
          git fetch
          git checkout ${{ inputs.wing-head }}
        working-directory: wing

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          author: daebot <dae@v2raya.org>
          committer: daebot <dae@v2raya.org>
          token: ${{ secrets.GH_TOKEN }}
          signoff: false
          base: main
          branch: ${{ inputs.pr_branch }}
          delete-branch: true
          title: ${{ inputs.wing-sync-message }}
          body: |
            Auto sync upstream process finished! Automated by @daebot
          labels: |
            automated-pr
          assignees: daebot
          team-reviewers: |
            daed
          draft: false
